import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Amazon.com. Spend less. Smile more.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="apple-touch-icon" sizes="180x180" href="/icon180.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/icon32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/icon16.png" />
      </Head>
      <h1>hello Amazon!</h1>
    </div>
  );
}
